name: Trigger Docker Build
on:
  push:
    branches: [ "main" ]

jobs:
  trigger-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Docker repo
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Leaf2Landscape/raycloudtools_riegl/dispatches \
            -d '{"event_type":"raycloudtools-push","client_payload":{"repository":"${{ github.repository }}","sha":"${{ github.sha }}"}}'
